version: '3.9'

services:
  db:
    container_name: nsy_db
    build: database
    #ports:
    # - 33060:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}","--protocol","tcp"]
      interval: 3s
      timeout: 3s
      retries: 10
    #volumes:
    #  - "./db/volume:/var/lib/mysql"
    networks:
      - nsy_net

  yapp:
    container_name: nsy_yapp-1
    build: .
    networks:
      - nsy_net
    ports:
      - "${APP_PORT}:80"
    depends_on: 
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget db:3306"]
      interval: 2s
      timeout: 2s
      retries: 3  
  ok:
    image: busybox
    env_file: .env
    command: "sh -c 'sleep 10 && echo \"To run the application, open http://localhost:${APP_PORT}\nTo join the yapp container, execute in separate console: \ndocker exec -it nsy_yapp-1 bash \ndocker exec -it nsy_db bash\"'"
    depends_on:
      - yapp

networks:
  nsy_net:
    driver: bridge
 